
CMM train_err=0.0, err=0.0
Traceback (most recent call last):
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 675, in <module>
    margin_classifiers_perf(d=2,n=100,approx_tau=1, SNR=10, n_test=1e4, s=1, random_flip_prob=0, mixture=True, l2=True)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 286, in margin_classifiers_perf
    result = prob.solve()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 1003, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 607, in get_problem_data
    solving_chain = self._construct_chain(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\problems\problem.py", line 841, in _construct_chain
    return construct_solving_chain(self, candidate_solvers, gp=gp,
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 162, in construct_solving_chain
    reductions = _reductions_for_problem_class(problem, candidates, gp)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 94, in _reductions_for_problem_class
    raise DCPError(
cvxpy.error.DCPError: Problem does not follow DCP rules. Specifically:
The following constraints are not DCP:
var1 @ var1 <= 1.0 , because the following subexpressions are not:
|--  var1 @ var1