Traceback (most recent call last):
  File "C:\Users\gizem\Documents\GitHub\noisy_fair\train_multi.py", line 493, in <module>
    main()
  File "C:\Users\gizem\Documents\GitHub\noisy_fair\train_multi.py", line 404, in main
    model = model.to(device)
UnboundLocalError: local variable 'model' referenced before assignment