
====================l1=========================
CMM train_err=0.0, err=50.625003814697266
Traceback (most recent call last):
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 640, in <module>
    aspect_ratio_l1(d=100, n=100, change_d=True, n_runs=2, s=1, SNR=5)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 414, in aspect_ratio_l1
    err_mm, errs_avm_poly, err_train_mm, errs_train_avm_poly, err_mm_l1, errs_avm_poly_l1, err_train_mm_l1, errs_train_avm_poly_l1,  wmm_l2, w_l2, wmm_l1, w_l1 = margin_classifiers_perf(d=d,n=n,approx_tau=1, SNR=SNR, n_test=1e4, s=s, l1=True, random_flip_prob=sigma)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 308, in margin_classifiers_perf
    A_ub = torch.cat( [torch.cat([torch.eye(d), -torch.eye(d)], dim=1), torch.cat([-torch.eye(d), -torch.eye(d)], dim=1), torch.cat([-z_seq, torch.zeros(n, d)], dim=1), torch.cat([torch.zeros(1,d), torch.ones(1,d)], dim=1)], dim=0)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 40000000000 bytes.
Traceback (most recent call last):
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 640, in <module>
    aspect_ratio_l1(d=100, n=100, change_d=True, n_runs=2, s=1, SNR=5)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 414, in aspect_ratio_l1
    err_mm, errs_avm_poly, err_train_mm, errs_train_avm_poly, err_mm_l1, errs_avm_poly_l1, err_train_mm_l1, errs_train_avm_poly_l1,  wmm_l2, w_l2, wmm_l1, w_l1 = margin_classifiers_perf(d=d,n=n,approx_tau=1, SNR=SNR, n_test=1e4, s=s, l1=True, random_flip_prob=sigma)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 308, in margin_classifiers_perf
    A_ub = torch.cat( [torch.cat([torch.eye(d), -torch.eye(d)], dim=1), torch.cat([-torch.eye(d), -torch.eye(d)], dim=1), torch.cat([-z_seq, torch.zeros(n, d)], dim=1), torch.cat([torch.zeros(1,d), torch.ones(1,d)], dim=1)], dim=0)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 40000000000 bytes.
Traceback (most recent call last):
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 640, in <module>
    aspect_ratio_l1(d=100, n=100, change_d=True, n_runs=2, s=1, SNR=5)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 414, in aspect_ratio_l1
    err_mm, errs_avm_poly, err_train_mm, errs_train_avm_poly, err_mm_l1, errs_avm_poly_l1, err_train_mm_l1, errs_train_avm_poly_l1,  wmm_l2, w_l2, wmm_l1, w_l1 = margin_classifiers_perf(d=d,n=n,approx_tau=1, SNR=SNR, n_test=1e4, s=s, l1=True, random_flip_prob=sigma)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 308, in margin_classifiers_perf
    A_ub = torch.cat( [torch.cat([torch.eye(d), -torch.eye(d)], dim=1), torch.cat([-torch.eye(d), -torch.eye(d)], dim=1), torch.cat([-z_seq, torch.zeros(n, d)], dim=1), torch.cat([torch.zeros(1,d), torch.ones(1,d)], dim=1)], dim=0)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 40000000000 bytes.
Traceback (most recent call last):
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 640, in <module>
    aspect_ratio_l1(d=100, n=100, change_d=True, n_runs=2, s=1, SNR=5)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 414, in aspect_ratio_l1
    err_mm, errs_avm_poly, err_train_mm, errs_train_avm_poly, err_mm_l1, errs_avm_poly_l1, err_train_mm_l1, errs_train_avm_poly_l1,  wmm_l2, w_l2, wmm_l1, w_l1 = margin_classifiers_perf(d=d,n=n,approx_tau=1, SNR=SNR, n_test=1e4, s=s, l1=True, random_flip_prob=sigma)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 308, in margin_classifiers_perf
    A_ub = torch.cat( [torch.cat([torch.eye(d), -torch.eye(d)], dim=1), torch.cat([-torch.eye(d), -torch.eye(d)], dim=1), torch.cat([-z_seq, torch.zeros(n, d)], dim=1), torch.cat([torch.zeros(1,d), torch.ones(1,d)], dim=1)], dim=0)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 40000000000 bytes.
Traceback (most recent call last):
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 640, in <module>
    aspect_ratio_l1(d=100, n=100, change_d=True, n_runs=2, s=1, SNR=5)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 414, in aspect_ratio_l1
    err_mm, errs_avm_poly, err_train_mm, errs_train_avm_poly, err_mm_l1, errs_avm_poly_l1, err_train_mm_l1, errs_train_avm_poly_l1,  wmm_l2, w_l2, wmm_l1, w_l1 = margin_classifiers_perf(d=d,n=n,approx_tau=1, SNR=SNR, n_test=1e4, s=s, l1=True, random_flip_prob=sigma)
  File "c:\Users\gizem\Documents\GitHub\noisy_fair\mixture_outlier.py", line 308, in margin_classifiers_perf
    A_ub = torch.cat( [torch.cat([torch.eye(d), -torch.eye(d)], dim=1), torch.cat([-torch.eye(d), -torch.eye(d)], dim=1), torch.cat([-z_seq, torch.zeros(n, d)], dim=1), torch.cat([torch.zeros(1,d), torch.ones(1,d)], dim=1)], dim=0)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 40000000000 bytes.